import { LRParser } from '@lezer/lr';
import { styleTags, tags } from '@lezer/highlight';

const jsonHighlighting = styleTags({
  String: tags.string,
  Number: tags.number,
  "True False": tags.bool,
  PropertyName: tags.propertyName,
  Null: tags.null,
  ", :": tags.separator,
  "[ ]": tags.squareBracket,
  "{ }": tags.brace,
  "Esc": tags.escape
});

// This file was generated by lezer-generator. You probably shouldn't edit it.
const parser = LRParser.deserialize({
  version: 14,
  states: "'OOQOPOOOlOQO'#CtOOOO'#Cb'#CbOwOPO'#CfO!kOPO'#CmO!uOPO'#CrO#WOPO'#CrQOOOOOOOOO'#Cn'#CnO#oOQO,59`OOOO,59`,59`OOOO'#Ch'#ChO#zOPO'#CgO$SOPO,59QO$[OPO'#CwOOOO,59Q,59QO$dOPO,59QO$iOPO'#CxOOOO,59X,59XO$qOPO,59XO$xOPO,59XOOOO,59^,59^O$}OPO,59^OOOO-E6l-E6lOOOO1G.z1G.zOQOPO,59RO%`OPO,59RO%eOPO,59ROOOO1G.l1G.lO%mOPO'#CoO%uOPO,59cOQOPO'#CpO%}OPO,59dOOOO1G.s1G.sOOOO1G.x1G.xOOOO1G.m1G.mOQOPO1G.mO&VOPO1G.mOgOPO'#CgOOOO,59Z,59ZOOOO-E6m-E6mOOOO,59[,59[OOOO-E6n-E6nOOOO7+$X7+$XOQOPO7+$XOOOO<<Gs<<Gs",
  stateData: "&[~OQTORTOSTOTTOXRO`SOgUOiPO~OVWOiYOjWO~OW_Og]OiPO~OQTORTOSTOTTOXRO`SOiPO~O_bOgcO~P!SOgeOefX^fX_fXWfX~OQfORfOSfOTfOXRO`SOiPO~OVWOihOjWO~O]iOgjO~OWlOiPO~O^mOWkX~OWlO~O^oO_lX~O_qO~P#WO_qO~OgrOefa^fa_faWfa~O]tO~O]tOguO~OgvOiPO~O^mOWka~O^oO_la~O]|O~O",
  goto: "#fmPPPPPPnPPPnz!QPPPPn!Y!`!fP!lP#OPP#`#c[TOSiot|TfUcQ^RRwmS[RmTk]vQXPRgXQn^RxnQpaRzpQVOQaSQsiQyoQ{tR}|`QOSUciot|XZR]mvR`RRdS",
  nodeNames: "⚠ JsonText True False Null Number String Esc } { Object Property PropertyName : , ] [ Array",
  maxTerm: 28,
  nodeProps: [
    ["isolate", -2,6,12,""],
    ["openedBy", 8,"{",15,"["],
    ["closedBy", 9,"}",16,"]"]
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "+^~RnXY#PYZ#P]^#Ppq#bqr#urs#zs|#u|}$P}!O$W!O!Q#u!Q!R&S!R![&d![!]&w!]!}#u!}#O'O#O#P'V#P#Q(|#Q#Y#u#Y#Z)T#Z#b#u#b#c)t#c#h#u#h#i*_#i#o#u#o#p*x#p#q#u#q#r+P#r;'S#u;'S;=`+W<%lO#uP#USgPXY#PYZ#P]^#Ppq#PR#iSjQgPXY#PYZ#P]^#Ppq#PQ#zOjQ~$POi~R$WO^PjQR$]QjQ!Q!R$c!R![%qP$hRTP!O!P$q!g!h%V#X#Y%VP$tP!Q![$wP$|RTP!Q![$w!g!h%V#X#Y%VP%YR{|%c}!O%c!Q![%iP%fP!Q![%iP%nPTP!Q![%iP%vSTP!O!P$q!Q![%q!g!h%V#X#Y%VR&ZRTPjQ!O!P$q!g!h%V#X#Y%VR&kSTPjQ!O!P$q!Q![%q!g!h%V#X#Y%VR'OO]PjQR'VO`PjQ~'YXrs'u!P!Q'u#O#P'u#U#V'u#Y#Z'u#b#c'u#f#g'u#h#i'u#i#j'z~'zOV~~'}R!Q![(W!c!i(W#T#Z(W~(ZR!Q![(d!c!i(d#T#Z(d~(gR!Q![(p!c!i(p#T#Z(p~(sR!Q!['u!c!i'u#T#Z'uR)TO_PjQR)YPjQ#T#U)]P)`P#`#a)cP)fP#g#h)iP)lP#X#Y)oP)tORPR)yPjQ#i#j)|P*PP#`#a*SP*VP#`#a*YP*_OSPR*dPjQ#f#g*gP*jP#i#j*mP*pP#X#Y*sP*xOQPR+POXPjQR+WOWPjQQ+ZP;=`<%l#u",
  tokenizers: [0, 1],
  topRules: {"JsonText":[0,1]},
  tokenPrec: 0
});

export { parser };
